apiVersion: v1
kind: ConfigMap
metadata:
  name: arc-reactor-config
  namespace: arc-reactor
data:
  SERVER_PORT: "8080"
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_FLYWAY_ENABLED: "true"
  ARC_REACTOR_AUTH_PUBLIC_ACTUATOR_HEALTH: "true"

  ARC_REACTOR_APPROVAL_ENABLED: "true"
  ARC_REACTOR_TOOL_POLICY_ENABLED: "true"
  ARC_REACTOR_TOOL_POLICY_DYNAMIC_ENABLED: "true"
  ARC_REACTOR_OUTPUT_GUARD_ENABLED: "true"

  ARC_REACTOR_RAG_ENABLED: "true"
  ARC_REACTOR_RAG_INGESTION_ENABLED: "true"
  ARC_REACTOR_RAG_INGESTION_DYNAMIC_ENABLED: "true"

  ARC_REACTOR_CONCURRENCY_MAX_CONCURRENT_REQUESTS: "20"
  ARC_REACTOR_CONCURRENCY_REQUEST_TIMEOUT_MS: "30000"
  ARC_REACTOR_CONCURRENCY_TOOL_CALL_TIMEOUT_MS: "15000"
