apiVersion: v1
kind: Service
metadata:
  name: arc-reactor
  namespace: arc-reactor
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: arc-reactor
  ports:
    - name: http
      port: 80
      targetPort: 8080
