apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arc-reactor
  namespace: arc-reactor
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "75"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "75"
spec:
  ingressClassName: nginx
  rules:
    - host: arc-reactor.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: arc-reactor
                port:
                  number: 80
